name: shopware6_client
description: An (incomplete) API client for Shopware 6.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.0-395.0.dev <3.0.0"

dependencies:
  chopper: ^6.0.0
  chopper_generator: ^6.0.0
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.7.0
  logging: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ">2.3.0 <4.0.0"
  json_serializable: ^6.5.4
